### ISSUE TITLE
how do I use 'com.googlecode.iterm2.plist' ?

### ISSUE THREAD

**Issue by JSP19SCM59D** [changkun/dotfiles#1]
Hello, Since I'm new to iterm2 and I really like the style of your iterm2, it's really cool. But I really don't know what the function of the file of 'com.googlecode.iterm2.plist' and where should I put it in? Please help....

**Comment by changkun** [comment]
Hi, sorry for the very late response. I hope you have solved your problem. Instead of using `.plist`, you could simply import this file: https://github.com/changkun/dotfiles/blob/master/iterm2/changkun-dev.json

The `.plist` file is somehow not possible to use, and I personally don't really know why...
